# Generated by Django 4.2.13 on 2025-03-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
